#!/usr/bin/env sh

# Check branch name spelling
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
echo "Branch name: $BRANCH_NAME"
echo "'$BRANCH_NAME'" | yarn eslint --stdin -c .eslintrc-spellcheck.json --format=stylish 